name = "gartukbackend"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[kv_namespaces]]
binding = "ROOMS_KV"
id = "a4e9682f813f46e7a7bb9d328f67cd9a"
